using System;
using System.Collections.Generic;
using System.Linq; 
using System.Text;

namespace FincSystem.Models
{ 
	public class DatabaseLog  
	{
		
		/// <summary>
		/// Primary key for DatabaseLog records.
		/// </summary>
		public Int32 DatabaseLogID { get; set; }                                      
		
		/// <summary>
		/// The date and time the DDL change occurred.
		/// </summary>
		public DateTime PostTime { get; set; }                                      
		
		/// <summary>
		/// The user who implemented the DDL change.
		/// </summary>
		public String DatabaseUser { get; set; }                                      
		
		/// <summary>
		/// The type of DDL statement that was executed.
		/// </summary>
		public String Event { get; set; }                                      
		
		/// <summary>
		/// The schema to which the changed object belongs.
		/// </summary>
		public String Schema { get; set; }                                      
		
		/// <summary>
		/// The object that was changed by the DDL statment.
		/// </summary>
		public String Object { get; set; }                                      
		
		/// <summary>
		/// The exact Transact-SQL statement that was executed.
		/// </summary>
		public String TSQL { get; set; }                                      
		
		/// <summary>
		/// The raw XML data generated by database trigger.
		/// </summary>
		public String XmlEvent { get; set; }                                      
		         
	} 
}
			
	